ZTF_BAND_CHARS = ['g', 'r', 'i']
ZTF_BAND_NAMES = ['zg', 'zr', 'zi']
ZTF_BAND_NUMBERS = [1, 2, 3]

ZTF_BAND_NUMBER_TO_CHAR = dict(zip(ZTF_BAND_NUMBERS, ZTF_BAND_CHARS))
ZTF_BAND_NUMBER_TO_NAME = dict(zip(ZTF_BAND_NUMBERS, ZTF_BAND_NAMES))
ZTF_BAND_CHAR_TO_STRING = dict(zip(ZTF_BAND_CHARS, ZTF_BAND_NAMES))
ZTF_BAND_CHAR_TO_NUMBER = dict(zip(ZTF_BAND_CHARS, ZTF_BAND_NUMBERS))
ZTF_BAND_STRING_TO_NUMBER = dict(zip(ZTF_BAND_NAMES, ZTF_BAND_NUMBERS))
